### ISSUE TITLE
Consider adding MIT license option

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/hibitset#21]

**Comment by torkleyy** [comment]
Anybody opposed to this?

- [x] @Aceeri 
- [x] @WaDelma 
- [x] @kvark 
- [x] @Binero
- [x] @torkleyy

**Comment by kvark** [comment]
No opposition

**Comment by WaDelma** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Aceeri** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Binero** [comment]
I'm fine with this as well.

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by torkleyy** [comment]
This was fixed already.
