### ISSUE TITLE
Combine bitsets

### ISSUE THREAD

**Issue by Aceeri** [slide-rs/hibitset#24]
Would be good if we had a way to non-lazily combine 2 bitsets in a performant way.

Naive way is just:
```rust
for bit in bitset {
    other.add(bit);
}
```

**Comment by WaDelma** [comment]
I would like to look into this, if nobody else has started it.

**Comment by torkleyy** [comment]
I didn't, @Aceeri is quite busy with Specs PRs I think, so feel free to do it.

**Comment by torkleyy** [comment]
I think compound assignment operators could be used for this.
