### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by dbkaplun** [slide-rs/hibitset#31]
Thanks!

**Comment by WaDelma** [comment]
Ah it still has link to the old website that was brought down.
Thanks for noticing and telling!

It should link to: https://docs.rs/hibitset/

**Comment by dbkaplun** [comment]
Thanks so much for fixing the docs! Looks like the [Crate badge on the README](https://github.com/slide-rs/hibitset) and the [documentation link on crates.io](https://crates.io/crates/hibitset) have broken links as well.

**Comment by torkleyy** [comment]
@dbkaplun The crates io badge works for me. The documentation link will be fixed with the next release.

**Comment by dbkaplun** [comment]
Thanks, it works now. Looking forward to the next release @torkleyy!
