### ISSUE TITLE
Release version 0.6.3 on crates.io

### ISSUE THREAD

**Issue by lcnr** [slide-rs/hibitset#54]
The version on github is currently `0.6.3` which was not yet published on `crates.io`. 

I currently want to get https://github.com/amethyst/specs/pull/620 merged, this requires `BitIter::clone` and `BitIterAnd::clone` which were added after `0.6.2`.

**Comment by lcnr** [comment]
@WaDelma considering that you are still active here and I would really like to finish amethyst/specs#620, do you have the rights to do this?

**Comment by WaDelma** [comment]
I don't have rights to publish to crates.io

**Comment by azriel91** [comment]
Now you do :v:; I've begun doing the publishing (shall update here when it's done).

**Comment by azriel91** [comment]
Released:

* :label: tag: https://github.com/amethyst/hibitset/tree/0.6.3
* :card_file_box: GH releases: https://github.com/amethyst/hibitset/releases/tag/0.6.3
* :package: crates.io: https://crates.io/crates/hibitset/0.6.3

Also pushed tags for `0.6.{0,3}`

**Comment by lcnr** [comment]
Awesome!

Thanks :heart:
